### ISSUE TITLE
In Visual Studio 2022, double-clicking changed item in Pending Changes toggles its checkmark for including/excluding from the commit

### ISSUE THREAD

**Issue by fizixman83** [AmpScm/AnkhSVN#26]
I'm testing the latest Visual Studio 2022 compatible build at https://github.com/AmpScm/AnkhSVN/releases/tag/v2.9.87. When double-clicking a changed item in the Pending Changes window, the checkmark toggles its checked state. This happens no matter where in the item row you double-click, and regardless which option you have set in Tools -> Options -> Source Control -> Subversion Environment -> "When double clicking items in Pending Changes:" (either "Open the file in Visual Studio" or "Show changes in the current diff tool")

Here is a gif demonstrating the issue with me double-clicking items in the Pending Changes window and you can see the checkmark toggle each time: https://i.imgur.com/e4hEGkl.gif

Single-clicks do not toggle the checkbox (unless you single-click on the checkbox itself), nor does trying to open the file (or show changes) via the item's right-click menu.

You can imagine this is particularly frustrating when double-checking your changes before commit and you essentially uncheck/check the wrong items and accidentally botch your commit with garbage. I've been using AnkhSVN for many prior versions of Visual Studio and this behaviour is new to the VS2022 version, though I wouldn't be surprised if it's more of a Visual Studio issue than an AnkhSVN issue.

I'm on Windows 10, version 10.0.19042 and using Visual Studio 2022 version 17.0.1

**Comment by christiansita** [comment]
I had the same issue. You just need to configure a setting properly.
Go to **Tools** -> **Options** -> **Subversion Environment**
Then, set **'When double clicking items in Pending Changes'** to **'Show changes in the current diff tool'**
![image](https://user-images.githubusercontent.com/1882201/149274867-a36e1845-1a14-4e83-9e18-fee4514c9cf1.png)

**Comment by BjoernEngelke** [comment]
I have the same Issue

Microsoft Visual Studio Professional 2022 (64-bit) 
Version 17.0.4

**Comment by LTrunda** [comment]
The issue still present ..... Version 17.1.1

**Comment by LTrunda** [comment]
I just debugged the issue and know how to solve it. But I don't know how to proceed the fix ... is here any "how to" help?

Solution (not nice :-)) - simply invert Checked value:
![screen_2022-04-20 09 49 31](https://user-images.githubusercontent.com/16815200/164179768-4525a22b-966c-42cd-8c2e-ca43d73d0af0.png)

**Comment by rhuijben** [comment]
Can you send a pull request?

**Comment by LTrunda** [comment]
Please how? I don't have rights to push new branch to create new pull request. Sorry but I'm not a common GIT user, so maybe I'm doing it in wrong way :-)

**Comment by fizixman83** [comment]
If this is an isolated bug from other users, I'd be concerned that this would probably introduce the undesired checkmark behaviour to them.

This does fix it for me though. Albeit you see the box toggle its check state back and forth for the fraction of a second. Still way more desirable result than having it remain permanently changed. Good job figuring something out!

**Comment by rhuijben** [comment]
> Please how? I don't have rights to push new branch to create new pull request. Sorry but I'm not a common GIT user, so maybe I'm doing it in wrong way :-)

The usual step on GitHub is to create a fork and push your Changes there, and the create a pull request.

Forking can be done from the GitHub site, and if you really want to, you can create the branch with any git or Subversion client, as GitHub supports Subversion clients ;-)

**Comment by LTrunda** [comment]
Thanks @rhuijben .... done ;-)

**Comment by rhuijben** [comment]
Should be resolved via pull request https://github.com/AmpScm/AnkhSVN/pull/46, thanks @LTrunda!
