### ISSUE TITLE
VS 2022 Crashing when Right Click on Pending Changes files

### ISSUE THREAD

**Issue by sabasjon** [AmpScm/AnkhSVN#34]
We just installed the VS2022 VSIX and found an issue where if we try and right click on any of the files listed in the 'Pending Changes' window then NO menu appears (we get the Windows 10 blue spinning wait icon) and then VS2022 closes (crashes) after approx 5-10 sec, and then it starts back up by itself.  

I am running:
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.0
AnhkSVN 2.9.87.0

If we right click on the file in Solution Explorer then it works fine (I can select Show Changes menu item) - its only when trying to right click in the Pending Changes tool window that we get no contextual menu and causes the crash.

I have also tried this with no solution open in VS 2022 - so right click on the 'empty' Pending Changes tool window and it still crashes.  

VS 2022 also displays this at the top when it restarts

![image](https://user-images.githubusercontent.com/11357950/155730877-ab4edf52-903f-4de8-8c39-5c156643f00a.png)

**Comment by LTrunda** [comment]
Log item from Event Viewer after this crash.... (OverflowException)

![image](https://user-images.githubusercontent.com/16815200/160098189-8aa2f3b3-847d-42e5-a5a3-aa0ae3e978f8.png)

**Comment by sabasjon** [comment]
Since raising this issue - we have found the 'Right Click' crash is happening on other screens within AnkhSVN - for example - when we bring up the 'History Viewer' window on a particular file - if you right click on that window then VS2022 also crashes and restarts.  It seems the only place we can 'Right Click' is in the Solution Explorer window itself - other places just crash Visual Studio

**Comment by LTrunda** [comment]
I just debugged the issue and know how to solve it. But I don't know how to proceed the fix ... is here any "how to" help?

Exception:
![screen_2022-04-20 09 13 11](https://user-images.githubusercontent.com/16815200/164179258-9f85fd21-7008-4231-b355-baa6dd3063a3.png)

Solution:
![screen_2022-04-20 09 49 09](https://user-images.githubusercontent.com/16815200/164179280-b3a3abe4-34f5-4c2a-b52f-aa32a72d30a2.png)

**Comment by rhuijben** [comment]
Should be resolved via pull request https://github.com/AmpScm/AnkhSVN/pull/46, thanks @LTrunda
