### ISSUE TITLE
Ignore-on commit issue in VS 2022

### ISSUE THREAD

**Issue by Stonesmith92** [AmpScm/AnkhSVN#43]
Found an issues with the file selection in VS 2022. Althoug the file is moved to ignore-on-commit Change list, every time I open a file it gets chacked and unchecked if i open it again from the pending chnages window. I don't know if it is a feature and if so how can you disable it?

**Comment by LTrunda** [comment]
Hello, it is the same as this issue https://github.com/AmpScm/AnkhSVN/issues/26

**Comment by Stonesmith92** [comment]
Thanks for the update, if i can will delete this issue then :)

**Comment by rhuijben** [comment]
Should be resolved via pull request #46, thanks @LTrunda
