### ISSUE TITLE
Merge Solution Fails in VS2017

### ISSUE THREAD

**Issue by rhuijben** [AmpScm/AnkhSVN#9]
While the version history is fixed, if I try to go to Pending Changes -> Update -> Merge Solution, and keep the default 'Merge a range of revisions' option selected, and hit next, VS freezes and eventually crashes with no error window.

_Originally posted by @jadonclegg in https://github.com/AmpScm/AnkhSVN/issues/8#issuecomment-843241868_

**Comment by rhuijben** [comment]
@jadonclegg More cases should be fixed in the next build. (Build 56 should have some interesting fixes).

**Comment by jadonclegg** [comment]
> @jadonclegg More cases should be fixed in the next build. (Build 56 should have some interesting fixes).

Build 56 fixed the merge solution for me.

**Comment by MiracleMick** [comment]
When will the new build be available? I was on auto-update and now I cannot merge. Thx

**Comment by MiracleMick** [comment]
Got #58, merge is fixed. Thx.

**Comment by rhuijben** [comment]
I just published version 58 to the Marketplace. Should be live soon.

**Comment by rhuijben** [comment]
Thanks @MiracleMick and @jadonclegg. Closing this issue now.
